services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: link-converter-app
    ports:
      - "8080:8080"
    environment:
      SPRING_COUCHBASE_CONNECTION_STRING: ${SPRING_COUCHBASE_CONNECTION_STRING}
      SPRING_COUCHBASE_USERNAME: ${SPRING_COUCHBASE_USERNAME}
      SPRING_COUCHBASE_PASSWORD: ${SPRING_COUCHBASE_PASSWORD}
      SPRING_COUCHBASE_BUCKET_NAME: ${SPRING_COUCHBASE_BUCKET_NAME}
      SPRING_PROFILES_ACTIVE: "couchbase"
    depends_on:
      - couchbase
    profiles: ["prod"]
  
  couchbase:
    image: couchbase:enterprise-7.6.3
    container_name: couchbase-db
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: ${COUCHBASE_ADMINISTRATOR_USERNAME}
      COUCHBASE_ADMINISTRATOR_PASSWORD: ${COUCHBASE_ADMINISTRATOR_PASSWORD}
    volumes:
      - couchbase_data:/opt/couchbase/var
      # TODO: This is only necessary when running load tests.
      - ./load-test/data:/opt/couchbase/import-data/load-test/data

volumes:
  couchbase_data:
