spring:
  application:
    name: link-converter
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  springdoc:
    api-docs:
      path: /api-docs
---
spring:
  config:
    activate:
      on-profile: postgres-redis
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
---
spring:
  config:
    activate:
      on-profile: couchbase
  couchbase:
    connection-string: ${SPRING_COUCHBASE_CONNECTION_STRING}
    username: ${SPRING_COUCHBASE_USERNAME}
    password: ${SPRING_COUCHBASE_PASSWORD}
    bucket-name: ${SPRING_COUCHBASE_BUCKET_NAME}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
